<?php

namespace App\Docs;

use OpenApi\Annotations as OA;

/**
 * @OA\Get(
 *     path="/items",
 *     tags={"Items"},
 *     summary="List all items",
 *     description="Get all items/services for the authenticated user's company",
 *     operationId="getItems",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(name="search", in="query", @OA\Schema(type="string")),
 *     @OA\Parameter(name="type", in="query", @OA\Schema(type="string", enum={"goods","service"})),
 *     @OA\Parameter(name="category_id", in="query", @OA\Schema(type="integer")),
 *     @OA\Parameter(name="is_active", in="query", @OA\Schema(type="boolean")),
 *     @OA\Response(response=200, description="Success", @OA\JsonContent(ref="#/components/schemas/SuccessResponse")),
 *     @OA\Response(response=401, description="Unauthorized", @OA\JsonContent(ref="#/components/schemas/ErrorResponse"))
 * )
 *
 * @OA\Get(
 *     path="/items/low-stock",
 *     tags={"Items"},
 *     summary="Get low stock items",
 *     description="Get items below reorder level",
 *     operationId="getLowStockItems",
 *     security={{"bearerAuth":{}}},
 *     @OA\Response(response=200, description="Success", @OA\JsonContent(ref="#/components/schemas/SuccessResponse"))
 * )
 *
 * @OA\Get(
 *     path="/items/{id}/history",
 *     tags={"Items"},
 *     summary="Get item stock and transaction history",
 *     description="Opening stock, purchases (qty in), sales (qty out), running balance. Stock is updated on purchase/sales invoices.",
 *     operationId="getItemHistory",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
 *     @OA\Parameter(name="date_from", in="query", @OA\Schema(type="string", format="date")),
 *     @OA\Parameter(name="date_to", in="query", @OA\Schema(type="string", format="date")),
 *     @OA\Parameter(name="per_page", in="query", @OA\Schema(type="integer", default=15)),
 *     @OA\Parameter(name="page", in="query", @OA\Schema(type="integer", default=1)),
 *     @OA\Response(response=200, description="Success", @OA\JsonContent(ref="#/components/schemas/SuccessResponse")),
 *     @OA\Response(response=404, description="Not found", @OA\JsonContent(ref="#/components/schemas/ErrorResponse"))
 * )
 *
 * @OA\Get(
 *     path="/items/{id}",
 *     tags={"Items"},
 *     summary="Get item by ID",
 *     operationId="getItem",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
 *     @OA\Response(response=200, description="Success", @OA\JsonContent(ref="#/components/schemas/SuccessResponse")),
 *     @OA\Response(response=404, description="Not found", @OA\JsonContent(ref="#/components/schemas/ErrorResponse"))
 * )
 *
 * @OA\Post(
 *     path="/items",
 *     tags={"Items"},
 *     summary="Create item",
 *     description="item_code is generated by the server as ITEM-001, ITEM-002, etc. Do not send item_code. opening_stock sets the opening quantity.",
 *     operationId="createItem",
 *     security={{"bearerAuth":{}}},
 *     @OA\RequestBody(required=true, @OA\JsonContent(
 *         required={"name","type"},
 *         @OA\Property(property="name", type="string", example="Widget A"),
 *         @OA\Property(property="type", type="string", enum={"goods","service"}),
 *         @OA\Property(property="category_id", type="integer", example=2),
 *         @OA\Property(property="hsn_sac_code", type="string", example="8471"),
 *         @OA\Property(property="tax_rate_id", type="integer", example=1),
 *         @OA\Property(property="purchase_price", type="number", format="float", example=100.00),
 *         @OA\Property(property="selling_price", type="number", format="float", example=150.00),
 *         @OA\Property(property="unit", type="string", example="nos"),
 *         @OA\Property(property="opening_stock", type="number", format="float", example=50, description="Opening quantity"),
 *         @OA\Property(property="reorder_level", type="number", format="float", example=10)
 *     )),
 *     @OA\Response(response=201, description="Created", @OA\JsonContent(ref="#/components/schemas/SuccessResponse")),
 *     @OA\Response(response=422, description="Validation error", @OA\JsonContent(ref="#/components/schemas/ErrorResponse"))
 * )
 *
 * @OA\Put(
 *     path="/items/{id}",
 *     tags={"Items"},
 *     summary="Update item",
 *     description="item_code is read-only. Updating opening_stock adjusts current_stock by the opening delta.",
 *     operationId="updateItem",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
 *     @OA\RequestBody(@OA\JsonContent(
 *         @OA\Property(property="name", type="string"),
 *         @OA\Property(property="selling_price", type="number", format="float"),
 *         @OA\Property(property="purchase_price", type="number", format="float"),
 *         @OA\Property(property="category_id", type="integer"),
 *         @OA\Property(property="tax_rate_id", type="integer"),
 *         @OA\Property(property="opening_stock", type="number", format="float", description="Opening quantity")
 *     )),
 *     @OA\Response(response=200, description="Updated", @OA\JsonContent(ref="#/components/schemas/SuccessResponse")),
 *     @OA\Response(response=404, description="Not found", @OA\JsonContent(ref="#/components/schemas/ErrorResponse"))
 * )
 *
 * @OA\Delete(
 *     path="/items/{id}",
 *     tags={"Items"},
 *     summary="Delete item",
 *     operationId="deleteItem",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
 *     @OA\Response(response=200, description="Deleted", @OA\JsonContent(ref="#/components/schemas/SuccessResponse")),
 *     @OA\Response(response=404, description="Not found", @OA\JsonContent(ref="#/components/schemas/ErrorResponse"))
 * )
 *
 * @OA\Get(
 *     path="/items/dropdown",
 *     tags={"Items"},
 *     summary="Items dropdown list",
 *     operationId="getItemsDropdown",
 *     security={{"bearerAuth":{}}},
 *     @OA\Response(response=200, description="Success", @OA\JsonContent(ref="#/components/schemas/SuccessResponse"))
 * )
 *
 * @OA\Patch(
 *     path="/items/{id}/status",
 *     tags={"Items"},
 *     summary="Toggle item active status",
 *     operationId="toggleItemStatus",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")),
 *     @OA\Response(response=200, description="Status updated", @OA\JsonContent(ref="#/components/schemas/SuccessResponse"))
 * )
 */
class ItemDocs
{
    //
}
