@if(!empty($exportMeta ?? null))
    <table style="width: 100%; border-collapse: collapse; margin: 0 0 10px 0; font-size: 10px;">
        <tr>
            <td style="border: 1px solid #d6dbe6; padding: 5px; background: #f8fafc; width: 18%;"><strong>Company</strong></td>
            <td style="border: 1px solid #d6dbe6; padding: 5px; width: 32%;">{{ $exportMeta['company_name'] ?? 'N/A' }}</td>
            <td style="border: 1px solid #d6dbe6; padding: 5px; background: #f8fafc; width: 18%;"><strong>Financial Year</strong></td>
            <td style="border: 1px solid #d6dbe6; padding: 5px; width: 32%;">{{ $exportMeta['financial_year'] ?? 'All' }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d6dbe6; padding: 5px; background: #f8fafc;"><strong>Period</strong></td>
            <td style="border: 1px solid #d6dbe6; padding: 5px;">{{ $exportMeta['date_from'] ?? 'N/A' }} to {{ $exportMeta['date_to'] ?? 'N/A' }}</td>
            <td style="border: 1px solid #d6dbe6; padding: 5px; background: #f8fafc;"><strong>Generated By</strong></td>
            <td style="border: 1px solid #d6dbe6; padding: 5px;">{{ $exportMeta['generated_by'] ?? 'System' }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #d6dbe6; padding: 5px; background: #f8fafc;"><strong>Generated At</strong></td>
            <td style="border: 1px solid #d6dbe6; padding: 5px;" colspan="3">{{ $exportMeta['generated_at'] ?? 'N/A' }}</td>
        </tr>
    </table>
@endif
